apiVersion: apps/v1
kind: Deployment
metadata:
  name: foxlybuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foxlybuntu
  template:
    metadata:
      labels:
        app: foxlybuntu
    spec:
      containers:
      - name: foxlybuntu
        image: ubuntu
        command: ["/bin/sleep", "3650d"]
        ports:
        - containerPort: 80
